import type { DroneDetection } from "../schemas/drone-detection.js";
export declare function saveDroneDetection(d: DroneDetection, rawId?: bigint): Promise<any>;
export declare function saveDroneDetectionFromFrame(obj: {
    droneId: string;
    deviceTs: Date;
    lat: number;
    lon: number;
    altM: number;
    speedMps: number;
    sourceId: string;
    type?: string;
    confidence?: number;
    bbox?: [number, number, number, number];
    frameId?: bigint;
    rawId?: bigint;
}): Promise<any>;
export declare function getLatestDroneDetection(droneId?: string): import("@prisma/client").Prisma.Prisma__DroneDetectionClient<{
    type: string | null;
    confidence: number | null;
    id: bigint;
    receivedAt: Date;
    deviceTs: Date;
    droneId: string;
    latDeg: number;
    lonDeg: number;
    altM: number;
    speedMps: number;
    radiusM: number | null;
    angleDeg: number | null;
    sourceId: string | null;
    bboxX: number | null;
    bboxY: number | null;
    bboxW: number | null;
    bboxH: number | null;
    frameId: bigint | null;
    rawId: bigint | null;
} | null, null, import("@prisma/client/runtime/library").DefaultArgs, import("@prisma/client").Prisma.PrismaClientOptions>;
export declare function listDetections(droneId: string, limit?: number): import("@prisma/client").Prisma.PrismaPromise<{
    type: string | null;
    confidence: number | null;
    id: bigint;
    receivedAt: Date;
    deviceTs: Date;
    droneId: string;
    latDeg: number;
    lonDeg: number;
    altM: number;
    speedMps: number;
    radiusM: number | null;
    angleDeg: number | null;
    sourceId: string | null;
    bboxX: number | null;
    bboxY: number | null;
    bboxW: number | null;
    bboxH: number | null;
    frameId: bigint | null;
    rawId: bigint | null;
}[]>;
//# sourceMappingURL=drone-detections.d.ts.map